[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "https://ekspert-finansowy.netlify.com"
  to = "https://ekspert-finansowy.biz"
  force = true

[[redirects]]
  from = "https://ekspert-finansowy.netlify.com/*"
  to = "https://ekspert-finansowy.biz/:splat"
  force = true